ENTITIES = {
  'player':{
    'sheetname':'assets/spritesheets/player.png',
    
    'walk_down':{
      'left':6,
      'top':3,
      'width':44,
      'height':58,
      'spacing':20,
      'length':4,
      'timer':10
      },
    'walk_left':{
      'left':6,
      'top':67,
      'width':44,
      'height':58,
      'spacing':20,
      'length':4,
      'timer':10
      },
    'walk_right':{
      'left':6,
      'top':129,
      'width':44,
      'height':58,
      'spacing':20,
      'length':4,
      'timer':10
      },
    'walk_up':{
      'left':6,
      'top':197,
      'width':44,
      'height':58,
      'spacing':20,
      'length':4,
      'timer':10
      }
  }
}